### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by joshuaj1397** [DankMemer/imgen#11]
Everything is very vague and I'm kind of confused on how the api keys are validated and invalidated. More documentation over how the system works would be appreciated.

**Comment by melmsie** [comment]
Most of this is legacy code from an old developer. I'd like to make a lot of changes but lacking a lot of the time and knowledge needed.

Once someone has time to improve some stuff (or if I eventually do), I will be sure to document better and add example configs.
