### ISSUE TITLE
Cluster Express Server

### ISSUE THREAD

**Issue by melmsie** [DankMemer/imgen#2]
It would greatly help the performance of the image commands if they were clustered. I'm not sure whether the cluster would be of server.js or the individual image commands as I don't have much experience with clustering.

For reference, there are usually 10k-20k image commands ran per day, so single thread is hurting.

**Comment by Sn0wFox** [comment]
Maybe you're looking after something like [pm2](http://pm2.keymetrics.io/) and its [cluster mode](http://pm2.keymetrics.io/docs/usage/cluster-mode/).

#hacktoberfestBroughtMeHere

**Comment by deziev** [comment]
#4
