### ISSUE TITLE
Ratelimits per API key

### ISSUE THREAD

**Issue by melmsie** [DankMemer/imgen#5]
I would like ratelimits per key some how. I plan on giving people keys to use the image server, and I would like a "very ratelimited" kind of key, and a "meh ratelimited" kind of key. Then also a master key with no ratelimits.

**Comment by joshuaj1397** [comment]
Are you wanting a kind of system like refresh tokens where a key automatically expires after a while for security or are you wanting like a key system for issuing keys based on user roles?

**Comment by melmsie** [comment]
@joshuaj1397 I'll be giving out free keys for people to use, and don't want my server spammed to hell. The keys expiring after like 30 days wouldn't be a bad idea, but the main focus would be on the rate-limiting endpoints.

**Comment by joshuaj1397** [comment]
@melmsie Okay cool, I'll work on this!

**Comment by melmsie** [comment]
@joshuaj1397 awesome, thanks
