### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by BlueADV** [DankMemer/imgen#51]
Hello, can you create an installation video or give more details about installation? I've installed all the requirements and after I use ./start.sh and accessing /api/crab (for example) it says rethinkdb has no attribute 'table' on line 63 file server.py. I'm using CentOS 6 and Python 3.6.

**Comment by melmsie** [comment]
You have rethink installed?

**Comment by GeoffreyWesthoff** [comment]
Make sure you have inserted the tables "keys" and "applications". Make sure to add yourself as an admin to the config and you should be able to access the admin panel and create a key
