### ISSUE TITLE
Redis?

### ISSUE THREAD

**Issue by Roki100** [DankMemer/imgen#58]
**Describe the bug**
redis error but it says it only requires rethinkdb?

**To Reproduce**
1. install only modules and rethinkdb
2. Start it
3. Open it in browser

**Expected behavior**
Site load and work.

**Screenshots**
None.

**Desktop (please complete the following information):**
 - OS: Host: Ubuntu 16.04, Me: Windows 10
 - Browser: chrome
 - Version: doesnt matter

**Additional context**
`redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.`

**Comment by aetheryx** [comment]
redis is very much so used for ratelimiting

**Comment by Roki100** [comment]
ok so i installed redis now im getting `Invalid OAuth2 redirect_uri` after pressing dashboard.
how to fix

**Comment by AndyTempel** [comment]
Make sure your config is set-up correctly. This software is provided as-is and we don't really provide support unless you encounter a bug or such issue.

**Comment by Roki100** [comment]
yes its set up correctly ._.

**Comment by aetheryx** [comment]
> This software is provided as-is and we don't really provide support unless you encounter a bug or such issue.

**Comment by Roki100** [comment]
then fix this "software" if it doesnt work ok?
i have made config filled it from example, pressing dashboard gives invalid redirect uri but from discord generator it works, but after pressing dashboard it requires me to auth again and it redirects to this broken site, so thats not my fault, thats this "software" bug

**Comment by aetheryx** [comment]
we clearly don't have this issue in our production configuration. you seem to have a sense of entitlement, assuming we provide selfhost support.. we don't. this repository is open sourced for transparency and educational purposes. anyone who wants to self host an instance is expected to be savvy enough to know what they're doing

**Comment by Roki100** [comment]
then whats this "production configuration" lol? i didnt changed anything

**Comment by aetheryx** [comment]
you're missing the point - we don't provide selfhost support, end of story
