### ISSUE TITLE
General Performance Cleanup

### ISSUE THREAD

**Issue by melmsie** [DankMemer/imgen#6]
The image commands feel slow and clunky sometimes, especially after running for a while. I also know they aren't all perfect as far as logic.

If you could clean up the server code and/or the code for commands to make it run better, it would be appreciated. 

Hacktoberfest peeps welcome!

**Comment by melmsie** [comment]
Also should be noted, this will be linted to [standardjs](https://standardjs.com/) later. Feel free to follow that, or if you don't whatever. I'll lint later.

**Comment by sebiglesias** [comment]
I can help you out with that

**Comment by sebiglesias** [comment]
I forked your project and made a branch where I correct your js syntax according to standardjs

**Comment by sebiglesias** [comment]
I didn't fix the performance issue, but I standarized your code and fixed some duplicated things you had on your assets

**Comment by sebiglesias** [comment]
@melmsie I made a PR about that
