### ISSUE TITLE
The website is not loading - Connection refused?

### ISSUE THREAD

**Issue by mynameismax** [DankMemer/imgen#75]
I downloaded this and installed all of the required pip packages. When I do ./start.sh, it says:
`[2020-07-21 06:15:02 +0000] [29546] [INFO] Starting gunicorn 20.0.4`
`[2020-07-21 06:15:02 +0000] [29546] [INFO] Listening at: http://127.0.0.1:65535 (29546)`
`[2020-07-21 06:15:02 +0000] [29546] [INFO] Using worker: gevent`
`[2020-07-21 06:15:02 +0000] [29549] [INFO] Booting worker with pid: 29549`
`[2020-07-21 06:15:02 +0000] [29550] [INFO] Booting worker with pid: 29550`
`[2020-07-21 06:15:02 +0000] [29551] [INFO] Booting worker with pid: 29551`
`[2020-07-21 06:15:03 +0000] [29552] [INFO] Booting worker with pid: 29552`
`[2020-07-21 06:15:03 +0000] [29553] [INFO] Booting worker with pid: 29553`
`[2020-07-21 06:15:03 +0000] [29554] [INFO] Booting worker with pid: 29554`
`[2020-07-21 06:15:03 +0000] [29555] [INFO] Booting worker with pid: 29555`
`[2020-07-21 06:15:03 +0000] [29556] [INFO] Booting worker with pid: 29556`
`[2020-07-21 06:15:03 +0000] [29557] [INFO] Booting worker with pid: 29557`
`[2020-07-21 06:15:03 +0000] [29558] [INFO] Booting worker with pid: 29558`
`[2020-07-21 06:15:03 +0000] [29559] [INFO] Booting worker with pid: 29559`
`[2020-07-21 06:15:03 +0000] [29560] [INFO] Booting worker with pid: 29560`
`[2020-07-21 06:15:03 +0000] [29561] [INFO] Booting worker with pid: 29561`
`[2020-07-21 06:15:03 +0000] [29562] [INFO] Booting worker with pid: 29562`
`[2020-07-21 06:15:03 +0000] [29563] [INFO] Booting worker with pid: 29563`
`[2020-07-21 06:15:03 +0000] [29564] [INFO] Booting worker with pid: 29564`
`[2020-07-21 06:15:03 +0000] [29565] [INFO] Booting worker with pid: 29565`
`[2020-07-21 06:15:03 +0000] [29566] [INFO] Booting worker with pid: 29566`
`[2020-07-21 06:15:03 +0000] [29567] [INFO] Booting worker with pid: 29567`
`[2020-07-21 06:15:04 +0000] [29568] [INFO] Booting worker with pid: 29568`
`[2020-07-21 06:15:04 +0000] [29570] [INFO] Booting worker with pid: 29570`
`[2020-07-21 06:15:04 +0000] [29569] [INFO] Booting worker with pid: 29569`
`[2020-07-21 06:15:04 +0000] [29571] [INFO] Booting worker with pid: 29571`
`[2020-07-21 06:15:04 +0000] [29572] [INFO] Booting worker with pid: 29572`

So, no errors. But, it just stays at that forever until I stop it. I'm not sure if it is supposed to say anything else, though. 

The main issue is that the web page is not working. I just get a connection refused error. Any ideas as to why this is happening? And, if you know why and have a solution, please share it. Thanks!

**Comment by NotII** [comment]
Are you trying to get to the page locally or is it hosted on a vps. 
its getting hosted locally you can see by the ip

**Comment by mynameismax** [comment]
How would I make it not only be locally accessible? Should I try a reverse proxy?

**Comment by NotII** [comment]
in start.sh specify the ip address, or use 0.0.0.0
mines looks like this
`gunicorn3 -w 24 -b 0.0.0.0:80 -k gevent server:app`

**Comment by kablekompany** [comment]
This isn't really an appropriate open issue as self hosting support outside of the current direction given within the repository readme isn't offered currently.
